# Site configuration for development
# Override properties in _config.yml, if jekyll serve --config "_config.yml,_config_dev.yml" used.

# Server

# Overridden by --host <value> command line option
host: "localhost"
# Overridden by --port <value> command line option
port: 4000
# Overridden by --livereload command line option
livereload: false

url: "http://localhost:4000"

# Build

sass:
  style: "full"

# Plugins

plugins:
  # Need to repeat plugins for production mode here
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"
  - "jekyll-paginate"
  - "jemoji"
  # Only development mode
  - "jekyll-admin"
