# Site configuration for development
# Override properties in _config.yml, if jekyll serve --config "_config.yml,_config_dev.yml" used.

# Server

host: "localhost" # overridden by --host option of jekyll serve command line
port: 4000 # overridden by --port option of jekyll serve command line

livereload: false # overridden by --livereload option of jekyll serve command line

# Info

url: "http://localhost:4000"

# Build

sass:
  style: "full"

# Plugins

plugins:
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"
  - "jekyll-paginate"
  - "jemoji"
  - "jekyll-admin" # only dev
