# Site configuration for production
# _config.yml
# See default configuration: https://jekyllrb.com/docs/configuration/default .

# Server

url: "https://glegoux.com"
baseurl: ""
detach: false
show_dir_listing: false
encoding: "utf-8"

# GitHub settings

# /!\ Some configuration settings cannot be changed for GitHub Pages sites.
# See https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll .
# These below settings are forced by GitHub.
github: ["metadata"]

lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build

source: "."
data_dir: "./_data"
layouts_dir: "./_layouts"
includes_dir: "./_includes"
plugins_dir: "./_plugins"
destination: "./_site"

show_drafts: false

sass:
  sass_dir: "_sass"
  style: "compressed"

exclude:
  - "bin/"
  - "CNAME"
  - "Makefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "VERSION"
  - "LICENSE"
  # Force to ignore some files for the watcher (with --watch option) in the Jekyll::Watcher, it is
  # normally already ignore by `jekyll build` (files starting by ., #, ~ and _).
  # See https://help.github.jp/enterprise/2.11/user/articles/files-that-start-with-an-underscore-are-missing/
  - ".idea/"
  - ".git"
  - ".gitignore"
  - ".gitattributes"
  - ".ruby-version"
  - ".sass-cache"
  - ".jekyll-metadata"
  - ".jekyll-cache"
  - ".jekyll-config-debug.json" # personal file to debug
  - "_config.yml"
  - "_config_dev.yml"
  - "_site/"

# Plugins

plugins:
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"
  - "jekyll-paginate"
  - "jemoji"

# Layout

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      article: true
      comment: true

# SEO

title: "Software Engineering Blog - Gilles Legoux"
description: "Personal blog about software engineering"
author: "Gilles Legoux"
keywords: "glegoux,Gilles,Legoux,informatics,mathematics"
logo: "/static/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"
