blog:
  title_header: "@GillesLegoux (glegoux)"
  title: "Software Engineering"
  keywords: ["Research & Development", "Algorithm", "Data", "Machine Learning", "Web", "Security", "Applied Mathematics", "Reliability & Infrastructure", "Design", "System", "Methodology", "Business"]
  menu_items:
    - name: "Blog"
      link: "/blog/"
      class_icon: "fas fa-newspaper"
    - name: "About"
      link: "/about/"
      class_icon: "fas fa-user"
    - name: "Contact"
      link: "/contact/"
      class_icon: "fas fa-address-card"
  socials:
    - name: "LinkedIn"
      link: "https://www.linkedin.com/in/gilleslegoux"
      class_icon:  "fab fa-linkedin"
    - name: "Twitter"
      link: "https://twitter.com/gilleslegoux"
      class_icon: "fab fa-twitter"
    - name: "GitHub"
      link: "https://github.com/glegoux"
      class_icon:  "fab fa-github"
    - name: "SlideShare"
      link: "https://www.slideshare.net/gilleslegoux"
      class_icon: "fab fa-slideshare"
    - name: "MeetUp"
      link: "https://www.meetup.com/members/162515452"
      class_icon: "fab fa-meetup"
    - name: "Email"
      link: "https://www.glegoux.com/contact/email"
      class_icon:  "fas fa-paper-plane"
  link_status_availability: "http://status.glegoux.com"
lang:
  header_text: "Translates from English"
  original:
    code: "en"
    display_name: "English"
  others:
    - code: "zh-CN"
      display_name: "中文"
    - code: "fr"
      display_name: "Français"
google_analytics:
  code: "UA-155162630-1"
disqus_name: "glegoux-com"
theme:
  color: "#383b43"
authors:
  glegoux:
    firstname: "Gilles"
    lastname: "LEGOUX"
    job: "Software Engineer"
    company: "Criteo"
    follow_link: "https://www.linkedin.com/in/gilleslegoux"
article:
  source_code: "https://raw.githubusercontent.com/glegoux/jekyll-blog/develop/src/_posts"
  resources: "https://github.com/glegoux/articles-glegoux-com/tree/master/articles"
  static:
    url: "https://raw.githubusercontent.com/glegoux/articles-glegoux-com/master/articles"
    image:
      path: "images"
      suffix: ""
