blog:
  title_header: "@GillesLegoux (glegoux)"
  title: "Software Engineering"
  keywords: ["Research & Development", "Algorithm", "Data", "Machine Learning", "Web", "Security", "Applied Mathematics", "Reliability & Infrastructure", "Design", "System", "Methodology", "Business"]
  menu_items:
    - name: "Blog"
      link: "/blog/"
      class_icon: "fas fa-newspaper"
    - name: "About"
      link: "/about/"
      class_icon: "fas fa-user"
    - name: "Contact"
      link: "/contact/"
      class_icon: "fas fa-address-card"
lang:
  header_text: "Translates from English"
  original:
    code: "en"
    display_name: "English"
  others:
    - code: "zh-CN"
      display_name: "中文"
    - code: "fr"
      display_name: "Français"
article:
  static: "https://github.com/glegoux/articles-glegoux-com/tree/master/articles"
  source: "https://raw.githubusercontent.com/glegoux/jekyll-blog/develop/src/_posts"
  image:
    path: "images"
    suffix: ""
google_analytics:
  code: "UA-155162630-1"
disqus_name: "glegoux-com"
theme:
  color: "#383b43"
