# Site configuration
# See default configuration: https://jekyllrb.com/docs/configuration/default

# Server

url: "https://glegoux.com"
baseurl: ""

# SEO

title: "Software Engineering Blog - Gilles Legoux"
description: "Personal blog about software engineering"
author: "Gilles Legoux"
keywords: "glegoux,Gilles,Legoux,informatics,mathematics,software,engineer"
logo: "/_static/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/page/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"
