# Site configuration for development


# Server

url: "http://localhost:4000"
baseurl: ""

# /!\ Overridden by --host <value> command line option
host: "localhost"

# /!\ Overridden by --port <value> command line option
port: 4000

# /!\ Overridden by --livereload command line option (if present force to true)
livereload: false

# Plugins

plugins:
  # Need to repeat plugins from src/_core/_config.yml mode here
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-mentions"
  - "jekyll-redirect-from"
  - "jemoji"
  # Only development mode
  - "jekyll-admin"
