name: Publish static website

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show environment
      run: |
        echo "Operating System: $(cat /etc/issue.net)"
        echo "Working Directory: $(pwd)"
        echo "Shell: $SHELL"
    - uses: ruby/setup-ruby@v1 # use .ruby-version
    - name: Install project
      run: |
        echo "** Install ruby dependencies:"
        make install
    - name: Show versions
      run: |
        source ~/.profile
        echo "** Context ecosystem:"
        echo "git version: $(git --version)"
        echo "make version: $(make --version | head -1)"
        echo "bash version: $(bash --version | head -1)"
        echo "** Ruby ecosystem:"
        echo "ruby version: $(ruby --version)"
        echo "bundle version: $(bundle --version)"
        echo "jekyll version: $(jekyll --version 2> /dev/null)"
        echo -e "gem version:\n$(gem list)"
    - name: Build static website
      run: |
        source ~/.profile
        make build
        cp .github/files/* dest/
    - name: Deploy static website
      run: |
        git add --force dest/
        git stash --keep-index --include-untracked
        git stash save -m "Deploy static website"
        git fetch --all
        git checkout master
        git rm -rf --quiet .
        git stash pop --quiet
        mv dest/* .
        git add -A
        git config user.email ""
        git config user.name "GitHub Actions"
        git commit -m "Deploy static website" --author="GitHub Actions <>" --quiet
        git push
